export enum PLAN_FEATURE_API_PATHS {
  ROOT_PATH = 'plan-features/',
  CREATE_PATH = 'create',
  GET_PLAN_FEATURES_PATH = 'plan/:planId/features',
  GET_FEATURE_PLANS_PATH = 'feature/:featureId/plans',
  GET_PLAN_FEATURE_PATH = 'plan/:planId/feature/:featureId',
  UPDATE_PATH = 'plan/:planId/feature/:featureId',
  UPDATE_CONFIG_PATH = 'plan/:planId/feature/:featureId/configuration',
  UPDATE_LIMITS_PATH = 'plan/:planId/feature/:featureId/limits',
  ENABLE_PATH = 'plan/:planId/feature/:featureId/enable',
  DISABLE_PATH = 'plan/:planId/feature/:featureId/disable',
  TOGGLE_PATH = 'plan/:planId/feature/:featureId/toggle',
  DELETE_PATH = 'plan/:planId/feature/:featureId',
  DELETE_ALL_PATH = 'plan/:planId/features',
}
